services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      POSTGRES_DB: telusko
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
    ports:
      - '5432'
    labels:
      - "org.springframework.boot.service-connection=postgres"